### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Chomikmarkus** [muraenateam/necrobrowser#4]
Hello!
Followed all instructions to install necrobrowser
System Ubuntu 20.04 VPS
Node version: 12.22.11
Npm version: 8.5.5
Error after running node necrobrowser.js
root@vps168451:/opt/necrobrowser# node necrobrowser.js
(node:744075) UnhandledPromiseRejectionWarning: Error: Cannot find module '@muraenateam/puppeteer-cluster'
Require stack:
- /opt/necrobrowser/puppeteer/cluster.js
- /opt/necrobrowser/necrobrowser.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/necrobrowser/puppeteer/cluster.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:744075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:744075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Tried to install manually puppeteer-cluster same error!
Best regards

**Comment by Chomikmarkus** [comment]
So got next error about extrusionpath and profiles made mkdir and created those directories! Now i am getting 
![Screenshot_20220402-062103_JuiceSSH](https://user-images.githubusercontent.com/92059377/161364062-9d928ee7-c3a4-4022-8362-c52f9485b845.jpg)

**Comment by Chomikmarkus** [comment]
oot@ubuntu-s-2vcpu-4gb-ams3-01:/opt/necrobrowser/puppeteer# cd ..
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/necrobrowser# node necrobrowser.js
(node:977543) UnhandledPromiseRejectionWarning: Error: Cannot find module '@muraenateam/puppeteer-cluster'
Require stack:
- /opt/necrobrowser/puppeteer/cluster.js
- /opt/necrobrowser/necrobrowser.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/necrobrowser/puppeteer/cluster.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:977543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:977543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/necrobrowser#

**Comment by Chomikmarkus** [comment]
Tried install it on ubuntu 20.04, debian 10 and freebsd 12.2 all fails!

**Comment by Chomikmarkus** [comment]
Got it to work now ;)

**Comment by kwekudumebi** [comment]
please how did you get it to work
